### PR TITLE
Added mutmut to "used by" section of the docs

### PR DESCRIPTION
**Pull request by boxed**
Mutmut used to use baron but it's pretty much unmaintained. Moving to parso actually simplified my code quite a bit in addition to getting full python 3 support. So great and thank you a lot for this library!

### CODE REVIEW

**Comment by davidhalter** [comment]
Happy to see you are using it :)

~ Dave

**Comment by boxed** [comment]
As in it tries to recover from invalid syntax and stuff? Well ok, I don’t need that for sure. What are the implications of having that on?

**Comment by davidhalter** [comment]
Well, you will have no exceptions if the parser fails. Instead you will have ErrorNode and ErrorLeaf nodes in there. If you don't want error recovery, use `parso.parse(code, error_recovery=False)`.

**Comment by boxed** [comment]
Thanks! Fixed.

**Pull request merged**
