### PR TITLE
Drop support for EOL Python 2.6 and 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Python 2.6 and 3.3 are EOL and no longer receiving security updates (or any updates) from the core Python team.

They're also little used.

Here's the pip installs for parso from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  55.88% |        188,129 |
| 3.5            |  23.47% |         79,005 |
| 3.4            |  16.04% |         53,990 |
| 2.7            |   4.01% |         13,504 |
| 3.7            |   0.37% |          1,259 |
| 3.3            |   0.23% |            773 |
| 2.6            |   0.00% |             13 |
| 3.8            |   0.00% |              6 |

Source: `pypinfo --start-date -39 --end-date -10 --percent --pip --markdown parso pyversion`

### CODE REVIEW

**Comment by blueyed** [comment]
Makes sense IMHO, and would be nice to have for Jedi itself then.

**Comment by blueyed** [comment]
Ah, it's at https://github.com/davidhalter/jedi/pull/1019 already.

**Comment by hugovk** [comment]
Rebased to resolve merge conflict.

**Comment by hugovk** [comment]
Rebased to resolve merge conflict.

**Comment by hugovk** [comment]
Rebased to resolve merge conflict.

https://github.com/davidhalter/jedi/pull/1019 has been merged.

**Comment by Jamim** [comment]
Hello @hugovk,

Thank you for the effort!
Just in case, there still are conflicting files.

**Comment by hugovk** [comment]
Thanks! Yes, I resolved the conflicts but the CI failed, so I undid it and will redo it soon.

**Comment by hugovk** [comment]
Rebased!

**Comment by Jamim** [comment]
Hello @davidhalter,
Could you please take a look at this PR?
Thank you!

**Comment by davidhalter** [comment]
Why?

**Comment by davidhalter** [comment]
Thanks again for doing this. :)

**Comment by hugovk** [comment]
You're welcome! Next up: Python 2.7 and 3.4 are also now EOL. Is it time to remove those too?

**Comment by davidhalter** [comment]
For parso it will probably take at least another year to remove them. :) Jedi will hopefully be a bit sooner.

**Comment by hugovk** [comment]
Okay :)

By the way, here's the installs for December 2019, I've not seen any project with 2.7 numbers this low:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  52.90% | 1,778,461 |
| 3.7      |  27.45% |   922,950 |
| 3.5      |  10.20% |   342,901 |
| 3.4      |   4.23% |   142,245 |
| 3.8      |   3.84% |   129,258 |
| 2.7      |   1.07% |    35,989 |
| null     |   0.30% |    10,006 |
| 3.9      |   0.01% |       273 |
| 2.6      |   0.00% |         5 |
| 3.3      |   0.00% |         3 |
| 3.2      |   0.00% |         1 |
| Total    |         | 3,362,092 |

Source: `pip install -U pypistats && pypistats python_minor parso --last-month`

Jedi is similar:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  52.34% | 1,777,356 |
| 3.7      |  27.85% |   945,908 |
| 3.5      |  10.06% |   341,569 |
| 3.4      |   4.17% |   141,746 |
| 3.8      |   4.01% |   136,196 |
| 2.7      |   1.04% |    35,439 |
| null     |   0.51% |    17,380 |
| 3.9      |   0.01% |       413 |
| 2.6      |   0.00% |         4 |
| 3.3      |   0.00% |         3 |
| 3.2      |   0.00% |         1 |
| Total    |         | 3,396,015 |

Source: `pip install -U pypistats && pypistats python_minor jedi --last-month`

I can do a PR for Jedi, would you like both 2.7 and 3.4 together, or just one of them first?

Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.4 | 2014-03-16 | 2019-03-16

**Comment by davidhalter** [comment]
I'll have to talk to some users first that still depend on 2.7 support in Jedi, but I'm happy to let you remove support at that point. Once I know when Jedi retires 2.7, we can remove support for both together (3.4 support is basically free if you still support 2.7). I'll try to let you know once were at that point.

The problem with doing the pull request now is that Jedi changes so quickly that it makes it impossible to do a pull request now and not have a lot of merge conflicts in a year.

**Comment by davidhalter** [comment]
Python 2.7 downloads are so low, because a lot of them are driven by Ipython.

However it doesn't paint the full picture. Most editors vendor Jedi (e.g. VSCode), this means that a copy of Jedi is provided for both 2.7 and 3.x.

**Pull request merged**
