### PR TITLE
Travis CI -> GitHub Actions

### PR DESCRIPTION
**Pull request by gousaiyang**
Move from Travis CI to GitHub Actions (#155)

### CODE REVIEW

**Comment by davidhalter** [comment]
Just FYI I did the port for Jedi: github.com/davidhalter/jedi

Since it uses similar ideas you could probably find some inspiration there if some tests won't pass (though 3.10 is probably a different kind of beast :)).

**Comment by gousaiyang** [comment]
`coveralls` is working now. For 3.10, looks like either `parso` or `pytest` does not fully support 3.10 as for now. For Travis CI we had a config `allow_failures` to allow `nightly` to fail without failing the whole build. For GitHub Actions I'm using a similar thing `continue-on-error` for `3.10-dev`. The workflow is actually considered to be successful when we look at [the Actions tab](https://github.com/davidhalter/parso/actions), since all checks except `3.10-dev` passed, and `3.10-dev` is allowed to fail. But we may still see red cross marks ❌ displayed in some places, and it won't say "all checks passed". Maybe this is the current user experience of GitHub Actions `continue-on-error`.

**Comment by davidhalter** [comment]
Shouldn't we just remove support for 3.10 for now? Parso does not support 3.10 parsing in a meaningful way anyway and I'm pretty sure there are going to be a ton of issues because of the parser changes. So I'd rather start debugging once an actual rc is out.

**Comment by gousaiyang** [comment]
I've disabled `3.10-dev` build. Typically "experimental" builds are intended to discover incompatibility with `nightly` at an earlier time. But if the red cross mark is too annoying for us, it's totally fine to disable them for now.

**Comment by davidhalter** [comment]
Thanks a lot for this!

> But if the red cross mark is too annoying for us, it's totally fine to disable them for now.

I think that for now this is the better choice. I agree that we should probably work on 3.10 support though!

**Pull request merged**
