### PR TITLE
Fix unit tests in Python 3.10 (Closes: #192)

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
I've pushed a new version working on Python 3.9 (Debian stable), 3.10 and 3.11 (Debian unstable). Can you trigger the CI again? The initial patch was for Debian unstable where we don't have older Python versions.

**Comment by davidhalter** [comment]
This time it looks much better. I feel like the linter should still be fixed, but 3.6 is probably something I have to look at.

**Comment by davidhalter** [comment]
Is it allowed that I can push changes to this branch? Because I would probably fix the Python 3.6 error this way.

**Comment by davidhalter** [comment]
I just realized that 3.6 has been end of life for a year. Can you just remove it from the CI? I feel like that's probably the best way forward.

**Comment by jspricke** [comment]
I've updated the Python versions, can you trigger the CI again?
Also feel free to push to this branch.

**Comment by davidhalter** [comment]
Unfortunately still some errors. I have tried to change the rules when the tests are run. So I feel like the tests will be run now when anybody not new to GitHub opens a PR. So I feel like you should now be able to see the results quicker.

**Comment by jspricke** [comment]
Thanks for changing the CI restrictions. I assume the reduced coverage is ok? (all other tests pass now)

**Pull request merged**
