### PR TITLE
Add get_scope method to PythonMixin

### PR DESCRIPTION
**Pull request by robodair**
Helpful for navigating up the tree when I'm finding the scope to generate a docstring for!

### CODE REVIEW

**Comment by davidhalter** [comment]
I'll keep it open for now. I had a function in parso called `get_parent_scope` that did essentially the same. I'm not sure I want it here. It's now in https://github.com/davidhalter/jedi/blob/master/jedi/parser_utils.py.

I'll think about reintroducing it.

**Comment by robodair** [comment]
Should I also add a check for being a flow to match that functionality?

**Comment by davidhalter** [comment]
No it's fine for now. Not sure how I would want this function to look like at the moment. There's a reason why I removed it in the first place - scopes are a bit strangely defined.

**Comment by robodair** [comment]
Would it be better to have a more flexible implementation that gets given a list of types to look for? Or should something like this just be implemented in user's code instead?

**Comment by davidhalter** [comment]
Well, there's tree.search_ancestor if you need something like that. I don't think we need to have everything in parso. Methods should be in parso if they are usable for at least 50% of the projects and if they are clearly defined. Otherwise write the code in your code base. It's what I did in jedi as well. There's a ton of code that's not part of parso but actually uses it.

**Comment by robodair** [comment]
Good enough for me!

**Comment by davidhalter** [comment]
Didn't say I will never merge, just not now. I'll keep it open.

**Comment by davidhalter** [comment]
I'm not looking at merging this anytime soon. There is a chance that I will add it in the future, but for now I will close.

**Pull request closed without merging**
