### PR TITLE
ci: Travis: use dist=xenial

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
py26 is not available there anymore: https://travis-ci.org/davidhalter/parso/jobs/497411068

Ref: https://github.com/davidhalter/parso/pull/38

**Comment by davidhalter** [comment]
Just remove 2.6, next release will be without it.

**Comment by davidhalter** [comment]
I'm also a bit confused about pypy2.7-6.0, can we not just use pypy2.7?

**Comment by blueyed** [comment]
> I'm also a bit confused about pypy2.7-6.0, can we not just use pypy2.7?

No, that's the new name on Xenial.. Travis does not have an official list, but that works..

**Comment by davidhalter** [comment]
Looks good, thanks!

**Pull request merged**
